language: crystal
sudo: required
dist: trusty
services:
  - redis-server
  - memcached
install:
  - sudo apt-get install -y libleveldb-dev redis-server memcached
  - shards install
script:
  - crystal spec
